- name: Swarm manager details
  debug: msg='{{item}}'
  with_items:
  - '{{ swarm_manager_address }}'
  - '{{ swarm_manager_port }}' 

- name: Wait for docker in manager to start
  wait_for:
    host: "{{ swarm_manager_address }}"
    port: "{{ swarm_manager_port }}"
    timeout: 300

#- name: Get the worker join-token.
#  shell: docker swarm join-token -q worker
#  changed_when: False
#  register: docker_worker_token
#  delegate_to: "{{groups['swarm_mgr'][0]}}"

- name: Get the worker join-token.
  uri:
   url: 'http://{{swarm_manager_address}}:1337/join/worker'
   return_content: yes
  changed_when: False
  register: docker_worker_token

- name: Join the pending Swarm worker nodes.
  #shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ swarm_manager_address }}:{{ swarm_manager_port }}
  shell: docker swarm join --token "{{ docker_worker_token.content }}" {{ swarm_manager_address }}:{{ swarm_manager_port }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1 and docker_info.stdout.find('Swarm: pending') == -1"

